version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: solorent
#      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/solorent?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  dbdata:
