spring:
  datasource:
    url: jdbc:mysql://mysql:3306/solorent?createDatabaseIfNotExist=true
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: bitzlk01@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gemini:
  api:
    key:  ${GEMINI_API_KEY}

aws:
  s3:
    bucket-name: solorent
    region: eu-north-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}





