spring:
  datasource:
    url: jdbc:mysql://mysql:3306/solorent?createDatabaseIfNotExist=true
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: bitzlk01@gmail.com
    password: iyht rvtp neic lwvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gemini:
  api:
    key: AIzaSyA119X8-1Ja1l6zNjzH2zmCCwSVvUw-bkA





